name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker buildx setup
      uses: docker/setup-buildx-action@v3.10.0
    - name: Build and push the docker image
      run: ./build.sh --push
